### ISSUE TITLE
'SliverHitTestResult' is not a subtype of type 'BoxHitTestResult'

### ISSUE THREAD

**Issue by pickupsb** [letsar/flutter_staggered_grid_view#121] opened 2020-06-11 02:32 UTC
when click an item,this err occurs. code:
`return Scaffold(
      appBar: AppBar(

        title: Text(widget.title),
      ),
      body: Center(

        child: new StaggeredGridView.countBuilder(
          controller: controller,
          crossAxisCount: 4,
          itemCount: 50,
          itemBuilder: (BuildContext context, int index) {

            return new

            Container(

              child: GestureDetector(

                child: new Text("1"),
                onTap: (){

                },
              ),

            );

          }
          ,
          staggeredTileBuilder: (int index) =>
          new StaggeredTile.count(2, index.isEven ? 2 : 1),
          mainAxisSpacing: 4.0,
          crossAxisSpacing: 4.0,
        ),
      ),
      floatingActionButton: FloatingActionButton(

        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: Icon(Icons.add),
      ), // This trailing comma makes auto-formatting nicer for build methods.
    );`

**Comment by sgehrman** [comment] 2020-06-11 11:37
same

**Comment by erabti** [comment] 2020-06-18 17:45
@pickupsb what version are you using?

**Comment by letsar** [comment] 2020-06-23 20:27
Dupe of #49

**Closed by letsar** 2020-06-23 20:27 UTC

**Comment by pickupsb** [comment] 2020-06-24 10:39
> @pickupsb what version are you using?

fixed with updating to the newest version

**Comment by pickupsb** [comment] 2020-06-24 10:40
> same

you can upgrade to the newest version,will fixed
