### ISSUE TITLE
 type 'SliverHitTestResult' is not a subtype of type 'BoxHitTestResult'

### ISSUE THREAD

**Issue by wuxinxi** [letsar/flutter_staggered_grid_view#111] opened 2020-03-25 05:10 UTC
use example :

RenderSliverVariableSizeBoxAdaptor.hitTestChildren (package:flutter_staggered_grid_view/src/rendering/sliver_variable_size_box_adaptor.dart:380:27)
E/flutter ( 2284): #1      RenderSliver.hitTest (package:flutter/src/rendering/sliver.dart:1269:11)
E/flutter ( 2284): #2      SliverHitTestResult.addWithAxisOffset (package:flutter/src/rendering/sliver.dart:844:31)
E/flutter ( 2284): #3      RenderSliverEdgeInsetsPadding.hitTestChildren (package:flutter/src/rendering/sliver_padding.dart:219:14)

**Comment by letsar** [comment] 2020-06-23 20:28
Dupe of #49

**Closed** 2020-10-10 12:39 UTC
