### ISSUE TITLE
Grid working in debug but not release

### ISSUE THREAD

**Issue by mayankjanmejay** [letsar/flutter_staggered_grid_view#128] opened 2020-07-16 15:52 UTC
Hi, 

I have successfully used your plugin in another of my apps that worked like a charm but I am having a bit of trouble with it at the moment. It works in Debug build of the app but not in the release version. 

I am using v0.3.0
I have attached images of how it looks in release and debug also attached the code, flutter doctor output & flutter analyze

**Release**
![Release](https://user-images.githubusercontent.com/35850067/87692358-58601300-c794-11ea-8d0c-0c1bcc94136a.PNG)

**Debug**
![Debug](https://user-images.githubusercontent.com/35850067/87692471-77f73b80-c794-11ea-8dc2-e58b83f16888.PNG)

```
class _AuctionHomeState extends State<AuctionHome> {

num run=0;

     ScrollController _arrowsController = ScrollController();
 var pageKey;
  @override
Widget build(BuildContext context) {

List<int> _sizes = [
    2,
    2,
    4,
    2,
    2,
    4,
    2,
    2,
    4,
    2,
    2,
    4,
    2,
    2,
    4,
    2,
    2,
    4,
    
  ];
  List<num> _other = [
    3,
    3,
    3,
    3,
    3,
    1,
    1,
    1,
    2,
    4,
    2,
    1,
    1,
    2,
    3,
    1,
    2,
    4,
  ];

  tileDeciderWidth(index)
  {
    if (index%2==0)
    {
      return 4;
    }
    else 
    return 2;
  }

 
num height=MediaQuery.of(context).size.height;
num width=MediaQuery.of(context).size.width;
num sS=MediaQuery.of(context).size.shortestSide;
    return Scaffold(
      key: pageKey,
           //appBar: AppBar(title: new Text(widget.title)           ),

           body:
             FutureBuilder<List<JAuction>>(
        future: fetchAuctions(),
        //fetchTools(limit: 200, startIndex: 1),
        builder: (context, snapshot) {
          if (snapshot.hasError) print(snapshot.error);
          if ( !snapshot.hasData)
          {
            return LoadingAnimationName(text:allTranslations.text('loading') ,);
          }
          if (snapshot.data.length==0)
{
return AnimatedErrorMessage(
  text: allTranslations.text('notFound'),
  icon: FontAwesomeIcons.userMinus,
  iconColor: Colors.red,

);
}

        return new StaggeredGridView.countBuilder(
          crossAxisCount: 4,
          itemCount: snapshot.data.length,          
          staggeredTileBuilder: (int index) =>
              new StaggeredTile.count(_sizes[index],width>height? 2:3),
          mainAxisSpacing: 4.0,
          controller: widget.controller,
          crossAxisSpacing: 4.0,
          itemBuilder: (context, index) => 
             GestureDetector(
            onTap: (){
               Navigator.of(context).push(
                    MaterialPageRoute(builder: (context) => SingleAuctionPage( snapshot.data[index].title,  snapshot.data[index].id)));
            },
            child:Expanded(flex: 1,child: SingleAuctionTile(document: snapshot.data[index],)),
              
        ));
        
        }),


         );;
  }
}
```

**flutter doctor -v**
```
[√] Flutter (Channel stable, v1.17.5, on Microsoft Windows [Version 10.0.18363.900], locale en-US)
    • Flutter version 1.17.5 at D:\flutter
    • Framework revision 8af6b2f038 (2 weeks ago), 2020-06-30 12:53:55 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4

 
[√] Android toolchain - develop for Android devices (Android SDK version 29.0.0)
    • Android SDK at C:\Users\Mayank\AppData\Local\Android\sdk
    • Platform android-29, build-tools 29.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    • All Android licenses accepted.

[√] Android Studio (version 3.6)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 44.0.2
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[√] VS Code (version 1.47.0)
    • VS Code at C:\Users\Mayank\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.12.2

[√] Connected device (1 available)
    • AOSP on IA Emulator • emulator-5554 • android-x86 • Android 9 (API 28) (emulator)

• No issues found!
```
**flutter analyze**
```
Analyzing Zaa...                                                        

   info - 'ControlledAnimation' is deprecated and shouldn't be used. See migration guide: https://pub.dev/packages/sa_v1_migration - lib\animations\wave.dart:25:16 - deprecated_member_use
   info - 'Playback' is deprecated and shouldn't be used. See migration guide: https://pub.dev/packages/sa_v1_migration - lib\animations\wave.dart:26:23 - deprecated_member_use
   info - 'MultiTrackTween' is deprecated and shouldn't be used. See migration guide: https://pub.dev/packages/sa_v1_migration - lib\animations\wave.dart:75:19 - deprecated_member_use
   info - 'Track' is deprecated and shouldn't be used. See migration guide: https://pub.dev/packages/sa_v1_migration - lib\animations\wave.dart:76:7 - deprecated_member_use
   info - 'Track' is deprecated and shouldn't be used. See migration guide: https://pub.dev/packages/sa_v1_migration - lib\animations\wave.dart:78:7 - deprecated_member_use
   info - 'ControlledAnimation' is deprecated and shouldn't be used. See migration guide: https://pub.dev/packages/sa_v1_migration - lib\animations\wave.dart:82:12 - deprecated_member_use
   info - 'Playback' is deprecated and shouldn't be used. See migration guide: https://pub.dev/packages/sa_v1_migration - lib\animations\wave.dart:83:17 - deprecated_member_use
   info - This class (or a class that this class inherits from) is marked as '@immutable', but one or more of its instance fields aren't final: AnimatedBackground.inComing, AnimatedBackground.inComingAppBar -     
          lib\animations\wave.dart:114:7 - must_be_immutable
   info - This class (or a class that this class inherits from) is marked as '@immutable', but one or more of its instance fields aren't final: CountDownClock.document - lib\components\countDownClock.dart:6:7 -
          must_be_immutable
   info - The value of the local variable 'countdownDuration' isn't used - lib\components\countDownClock.dart:17:9 - unused_local_variable
   info - This class (or a class that this class inherits from) is marked as '@immutable', but one or more of its instance fields aren't final: HtmlRender.htmlData - lib\components\htmlRender.dart:7:7 -
          must_be_immutable
   info - This class (or a class that this class inherits from) is marked as '@immutable', but one or more of its instance fields aren't final: PhotoViewer.photos - lib\components\photoViewer.dart:6:7 -
          must_be_immutable
   info - Unused import: 'package:flutter_swiper/flutter_swiper.dart' - lib\components\singleAuctionTile.dart:2:8 - unused_import
   info - Unused import: 'package:font_awesome_flutter/font_awesome_flutter.dart' - lib\components\singleAuctionTile.dart:3:8 - unused_import
   info - Unused import: 'package:ntp/ntp.dart' - lib\components\singleAuctionTile.dart:4:8 - unused_import
   info - Unused import: 'package:photo_view/photo_view.dart' - lib\components\singleAuctionTile.dart:5:8 - unused_import
   info - Unused import: 'package:slide_countdown_clock/slide_countdown_clock.dart' - lib\components\singleAuctionTile.dart:6:8 - unused_import
   info - Unused import: 'package:zaa/shared/allTranslations.dart' - lib\components\singleAuctionTile.dart:9:8 - unused_import
   info - Unused import: 'package:zaa/shared/exampleFunctionsHTTP.dart' - lib\components\singleAuctionTile.dart:12:8 - unused_import
   info - Unused import: 'package:zaa/shared/functions.dart' - lib\components\singleAuctionTile.dart:13:8 - unused_import
   info - Unused import: 'package:zaa/components/htmlRender.dart' - lib\components\singleAuctionTile.dart:17:8 - unused_import
   info - Unused import: 'package:zaa/shared/others.dart' - lib\components\singleAuctionTile.dart:18:8 - unused_import
   info - This class (or a class that this class inherits from) is marked as '@immutable', but one or more of its instance fields aren't final: SingleAuctionTile.document -
          lib\components\singleAuctionTile.dart:20:7 - must_be_immutable
   info - The value of the local variable '_arrowsController' isn't used - lib\components\singleAuctionTile.dart:61:5 - unused_local_variable
   info - Unused import: 'package:zaa/shared/app_localizations.dart' - lib\main.dart:4:8 - unused_import
   info - Unused import: 'package:zaa/shared/application.dart' - lib\main.dart:5:8 - unused_import
   info - Unused import: 'package:zaa/shared/functionsHTTP.dart' - lib\main.dart:6:8 - unused_import
   info - Unused import: 'package:zaa/shared/globals.dart' - lib\main.dart:7:8 - unused_import
   info - Unused import: 'package:zaa/shared/pageLogin.dart' - lib\main.dart:8:8 - unused_import
   info - Unused import: 'package:zaa/pages/auctions/auctionsMBandView.dart' - lib\pages\auctionsMain.dart:6:8 - unused_import
   info - Unused import: 'package:zaa/shared/pageLogin.dart' - lib\pages\auctionsMain.dart:12:8 - unused_import
   info - Avoid using braces in interpolation when not needed - lib\pages\auctionsMain.dart:35:75 - unnecessary_brace_in_string_interps
   info - The value of the local variable 'sS' isn't used - lib\pages\auctionsMain.dart:58:5 - unused_local_variable
   info - This class (or a class that this class inherits from) is marked as '@immutable', but one or more of its instance fields aren't final: AuctionHome.limit, AuctionHome.controller -
          lib\pages\auctions\auctionsHomePage.dart:11:7 - must_be_immutable
   info - The value of the field '_arrowsController' isn't used - lib\pages\auctions\auctionsHomePage.dart:25:23 - unused_field
   info - The value of the local variable '_other' isn't used - lib\pages\auctions\auctionsHomePage.dart:51:13 - unused_local_variable
   info - The declaration 'tileDeciderWidth' isn't referenced - lib\pages\auctions\auctionsHomePage.dart:72:3 - unused_element
   info - The value of the local variable 'sS' isn't used - lib\pages\auctions\auctionsHomePage.dart:85:5 - unused_local_variable
   info - Avoid empty statements - lib\pages\auctions\auctionsHomePage.dart:131:12 - empty_statements
   info - Dead code - lib\pages\auctions\auctionsHomePage.dart:131:12 - dead_code
   info - Unused import: 'package:draggable_scrollbar/draggable_scrollbar.dart' - lib\pages\auctions\auctionsMBandView.dart:1:8 - unused_import
   info - Unused import: 'package:zaa/pages/auctions/singleAuction/singleAuctionPageBuilder.dart' - lib\pages\auctions\auctionsMBandView.dart:4:8 - unused_import
   info - The value of the local variable 'sS' isn't used - lib\pages\auctions\auctionsMBandView.dart:30:5 - unused_local_variable
   info - The value of the local variable 'name' isn't used - lib\pages\auctions\auctionsMBandView.dart:92:8 - unused_local_variable
   info - Dead code - lib\pages\auctions\auctionsMBandView.dart:123:11 - dead_code
   info - Unused import: 'package:zaa/shared/exampleFunctionsHTTP.dart' - lib\pages\auctions\singleAuction\bidHistory.dart:7:8 - unused_import
   info - This class (or a class that this class inherits from) is marked as '@immutable', but one or more of its instance fields aren't final: BisHistory.auction -
          lib\pages\auctions\singleAuction\bidHistory.dart:11:7 - must_be_immutable
   info - The value of the local variable 'width' isn't used - lib\pages\auctions\singleAuction\bidHistory.dart:23:5 - unused_local_variable
   info - The value of the local variable 'sS' isn't used - lib\pages\auctions\singleAuction\bidHistory.dart:24:5 - unused_local_variable
   info - Unused import: 'package:zaa/shared/others.dart' - lib\pages\auctions\singleAuction\singleAuctionPage.dart:8:8 - unused_import
   info - This class (or a class that this class inherits from) is marked as '@immutable', but one or more of its instance fields aren't final: SingleAuction.auction -
          lib\pages\auctions\singleAuction\singleAuctionPage.dart:10:7 - must_be_immutable
   info - Unused import: 'package:zaa/pages/auctionsMain.dart' - lib\pages\auctions\singleAuction\singleAuctionPageBuilder.dart:5:8 - unused_import
   info - Unused import: 'package:zaa/shared/allTranslations.dart' - lib\pages\auctions\singleAuction\singleAuctionPageBuilder.dart:7:8 - unused_import
   info - The value of the local variable '_arrowsController' isn't used - lib\pages\auctions\singleAuction\singleAuctionPageBuilder.dart:46:22 - unused_local_variable
   info - This function has a return type of 'Future<bool>', but doesn't end with a return statement - lib\pages\auctions\singleAuction\singleAuctionPageBuilder.dart:49:7 - missing_return
   info - This function has a return type of 'Widget', but doesn't end with a return statement - lib\pages\auctions\singleAuction\singleAuctionPageBuilder.dart:92:18 - missing_return
   info - Unused import: 'package:font_awesome_flutter/font_awesome_flutter.dart' - lib\pages\categories.dart:2:8 - unused_import
   info - Unused import: 'package:fancy_bottom_navigation/fancy_bottom_navigation.dart' - lib\pages\categories.dart:6:8 - unused_import
   info - Duplicate import - lib\pages\categories.dart:7:8 - duplicate_import
   info - Unused import: 'package:zaa/pages/auctions/singleAuction/bidHistory.dart' - lib\pages\categories.dart:8:8 - unused_import
   info - Unused import: 'package:zaa/pages/auctions/singleAuction/singleAuctionPage.dart' - lib\pages\categories.dart:9:8 - unused_import
   info - Unused import: 'package:zaa/pages/auctionsMain.dart' - lib\pages\categories.dart:10:8 - unused_import
   info - Unused import: 'package:zaa/pages/search.dart' - lib\pages\categories.dart:11:8 - unused_import
   info - Unused import: 'package:zaa/shared/allTranslations.dart' - lib\pages\categories.dart:12:8 - unused_import
   info - Duplicate import - lib\pages\categories.dart:13:8 - duplicate_import
   info - Unused import: 'package:zaa/shared/globals.dart' - lib\pages\categories.dart:17:8 - unused_import
   info - The value of the local variable 'width' isn't used - lib\pages\categories.dart:32:5 - unused_local_variable
   info - The value of the local variable 'sS' isn't used - lib\pages\categories.dart:33:5 - unused_local_variable
   info - Unused import: 'package:google_fonts/google_fonts.dart' - lib\pages\categories\singleCategoriesLoader.dart:3:8 - unused_import
   info - Unused import: 'package:zaa/pages/categories/singleCategoriesLoader.dart' - lib\pages\categories\singleCategoriesLoader.dart:6:8 - unused_import
   info - The value of the local variable 'width' isn't used - lib\pages\categories\singleCategoriesLoader.dart:21:5 - unused_local_variable
   info - The value of the local variable 'sS' isn't used - lib\pages\categories\singleCategoriesLoader.dart:22:5 - unused_local_variable
   info - Avoid empty statements - lib\pages\categories\singleCategoriesLoader.dart:108:7 - empty_statements
   info - Dead code - lib\pages\categories\singleCategoriesLoader.dart:108:7 - dead_code
   info - The value of the local variable 'height' isn't used - lib\pages\profile\profileMain.dart:20:5 - unused_local_variable
   info - The value of the local variable 'sS' isn't used - lib\pages\profile\profileMain.dart:22:5 - unused_local_variable
   info - Unused import: 'package:zaa/pages/auctions/auctionsHomePage.dart' - lib\pages\search.dart:5:8 - unused_import
   info - Unused import: 'package:zaa/pages/auctions/auctionsMBandView.dart' - lib\pages\search.dart:6:8 - unused_import
   info - Unused import: 'package:zaa/shared/pageLogin.dart' - lib\pages\search.dart:12:8 - unused_import
   info - This class (or a class that this class inherits from) is marked as '@immutable', but one or more of its instance fields aren't final: SearchWidget.inComingWidget - lib\pages\search.dart:14:7 -
          must_be_immutable
   info - Avoid using braces in interpolation when not needed - lib\pages\search.dart:36:75 - unnecessary_brace_in_string_interps
   info - The value of the local variable 'sS' isn't used - lib\pages\search.dart:59:5 - unused_local_variable
   info - Unused import: 'package:google_fonts/google_fonts.dart' - lib\pages\tempPage.dart:3:8 - unused_import
   info - Unused import: 'package:zaa/pages/categories/singleCategoriesLoader.dart' - lib\pages\tempPage.dart:6:8 - unused_import
   info - The value of the local variable 'width' isn't used - lib\pages\tempPage.dart:21:5 - unused_local_variable
   info - The value of the local variable 'sS' isn't used - lib\pages\tempPage.dart:22:5 - unused_local_variable
   info - Avoid empty statements - lib\pages\tempPage.dart:105:7 - empty_statements
   info - Dead code - lib\pages\tempPage.dart:105:7 - dead_code
   info - Unused import: 'package:flutter_local_notifications/flutter_local_notifications.dart' - lib\pages\userMain.dart:4:8 - unused_import
   info - Unused import: 'package:zaa/pages/userProfile.dart' - lib\pages\userMain.dart:11:8 - unused_import
   info - Unused import: 'package:zaa/pages/tempPage.dart' - lib\pages\userMain.dart:12:8 - unused_import
   info - Unused import: '../main.dart' - lib\pages\userMain.dart:18:8 - unused_import
   info - Dead code - lib\pages\userMain.dart:100:4 - dead_code
   info - The declaration '_getPageOrig' isn't referenced - lib\pages\userMain.dart:119:3 - unused_element
   info - Unused import: 'dart:io' - lib\pages\userProfile.dart:1:8 - unused_import
   info - Unused import: 'package:font_awesome_flutter/font_awesome_flutter.dart' - lib\pages\userProfile.dart:6:8 - unused_import
   info - Unused import: 'package:image_picker/image_picker.dart' - lib\pages\userProfile.dart:7:8 - unused_import
   info - Unused import: 'package:zaa/animations/wave.dart' - lib\pages\userProfile.dart:9:8 - unused_import
   info - Unused import: 'package:zaa/shared/classesHTTP.dart' - lib\pages\userProfile.dart:10:8 - unused_import
   info - Unused import: 'package:zaa/shared/functions.dart' - lib\pages\userProfile.dart:11:8 - unused_import
   info - Duplicate import - lib\pages\userProfile.dart:15:8 - duplicate_import
   info - Unused import: 'package:image_picker/image_picker.dart' - lib\pages\userProfile.dart:15:8 - unused_import
   info - The value of the local variable 'stars' isn't used - lib\pages\userProfile.dart:31:16 - unused_local_variable
   info - This function has a return type of 'Future<bool>', but doesn't end with a return statement - lib\pages\userProfile.dart:40:20 - missing_return
   info - The value of the local variable 'documentID' isn't used - lib\pages\userProfile.dart:61:34 - unused_local_variable
   info - The value of the local variable 'displayName' isn't used - lib\pages\userProfile.dart:62:34 - unused_local_variable
   info - Unused import: 'package:url_launcher/url_launcher.dart' - lib\shared\classes.dart:6:8 - unused_import
   info - Unused import: 'package:zaa/shared/classesHTTP.dart' - lib\shared\cold.dart:4:8 - unused_import
   info - Equality operator `==` invocation with references of unrelated types - lib\shared\cold.dart:149:28 - unrelated_type_equality_checks
   info - Equality operator `==` invocation with references of unrelated types - lib\shared\cold.dart:149:38 - unrelated_type_equality_checks
   info - Unused import: 'package:zaa/shared/allTranslations.dart' - lib\shared\consts.dart:2:8 - unused_import
   info - Unused import: 'package:flutter/material.dart' - lib\shared\consts.dart:4:8 - unused_import
   info - Unused import: 'package:font_awesome_flutter/font_awesome_flutter.dart' - lib\shared\consts.dart:5:8 - unused_import
   info - Unused import: 'dart:io' - lib\shared\exampleFunctionsHTTP.dart:5:8 - unused_import
   info - Unused import: 'package:zaa/shared/functions.dart' - lib\shared\exampleFunctionsHTTP.dart:8:8 - unused_import
   info - Unused import: 'package:zaa/shared/globals.dart' - lib\shared\exampleFunctionsHTTP.dart:10:8 - unused_import
   info - Unused import: 'package:shared_preferences/shared_preferences.dart' - lib\shared\exampleFunctionsHTTP.dart:16:8 - unused_import
   info - The value of the local variable 'statusCode' isn't used - lib\shared\exampleFunctionsHTTP.dart:92:7 - unused_local_variable
   info - The value of the local variable 'body' isn't used - lib\shared\exampleFunctionsHTTP.dart:94:10 - unused_local_variable
   info - The value of the local variable 'headers' isn't used - lib\shared\exampleFunctionsHTTP.dart:109:23 - unused_local_variable
   info - The value of the local variable 'statusCode' isn't used - lib\shared\exampleFunctionsHTTP.dart:124:7 - unused_local_variable
   info - The value of the local variable 'client' isn't used - lib\shared\exampleFunctionsHTTP.dart:187:15 - unused_local_variable
   info - The value of the local variable 'statusCode' isn't used - lib\shared\exampleFunctionsHTTP.dart:195:7 - unused_local_variable
   info - The value of the local variable 'parsed' isn't used - lib\shared\exampleFunctionsHTTP.dart:197:9 - unused_local_variable
   info - The value of the local variable 'head' isn't used - lib\shared\exampleFunctionsHTTP.dart:432:7 - unused_local_variable
   info - Unused import: 'dart:convert' - lib\shared\functions.dart:2:8 - unused_import
   info - Unused import: 'dart:io' - lib\shared\functions.dart:3:8 - unused_import
   info - Unused import: 'dart:math' - lib\shared\functions.dart:4:8 - unused_import
   info - Unused import: 'package:zaa/shared/classes.dart' - lib\shared\functions.dart:6:8 - unused_import
   info - Unused import: 'package:zaa/shared/functionsHTTP.dart' - lib\shared\functions.dart:7:8 - unused_import
   info - Unused import: 'package:zaa/shared/pageLogin.dart' - lib\shared\functions.dart:8:8 - unused_import
   info - Unused import: 'package:zaa/shared/private.dart' - lib\shared\functions.dart:9:8 - unused_import
   info - Unused import: 'package:zaa/shared/translations.dart' - lib\shared\functions.dart:10:8 - unused_import
   info - Unused import: 'package:animated_text_kit/animated_text_kit.dart' - lib\shared\functions.dart:11:8 - unused_import
   info - Unused import: 'package:flutter_feather_icons/flutter_feather_icons.dart' - lib\shared\functions.dart:16:8 - unused_import
   info - Unused import: 'package:http/http.dart' - lib\shared\functions.dart:17:8 - unused_import
   info - Unused import: 'package:path_provider/path_provider.dart' - lib\shared\functions.dart:18:8 - unused_import
   info - Unused import: 'globals.dart' - lib\shared\functions.dart:21:8 - unused_import
   info - Duplicate import - lib\shared\functions.dart:23:8 - duplicate_import
   info - Unused import: 'dart:convert' - lib\shared\functions.dart:23:8 - unused_import
   info - Duplicate import - lib\shared\functions.dart:25:8 - duplicate_import
   info - Unused import: 'dart:io' - lib\shared\functions.dart:25:8 - unused_import
   info - This function has a return type of 'Future<bool>', but doesn't end with a return statement - lib\shared\functions.dart:322:14 - missing_return
   info - Unused import: 'package:zaa/shared/functions.dart' - lib\shared\functionsHTTP.dart:7:8 - unused_import
   info - Unused import: 'package:flutter/cupertino.dart' - lib\shared\functionsHTTP.dart:10:8 - unused_import
   info - Unused import: 'package:flutter/material.dart' - lib\shared\functionsHTTP.dart:12:8 - unused_import
   info - Unused import: 'package:shared_preferences/shared_preferences.dart' - lib\shared\functionsHTTP.dart:14:8 - unused_import
   info - This function has a return type of 'Future<String>', but doesn't end with a return statement - lib\shared\functionsHTTP.dart:38:16 - missing_return
   info - The value of the local variable 'headers' isn't used - lib\shared\functionsHTTP.dart:96:23 - unused_local_variable
   info - The value of the local variable 'parsed' isn't used - lib\shared\functionsHTTP.dart:104:9 - unused_local_variable
   info - The value of the local variable 'token' isn't used - lib\shared\functionsHTTP.dart:120:10 - unused_local_variable
   info - Unused import: 'package:zaa/shared/functionsHTTP.dart' - lib\shared\globals.dart:5:8 - unused_import
   info - Unused import: 'dart:io' - lib\shared\others.dart:1:8 - unused_import
   info - This class (or a class that this class inherits from) is marked as '@immutable', but one or more of its instance fields aren't final: ImageWithBroken.height, ImageWithBroken.width, ImageWithBroken.fit -
          lib\shared\others.dart:22:7 - must_be_immutable
   info - This class (or a class that this class inherits from) is marked as '@immutable', but one or more of its instance fields aren't final: AnimatedErrorMessage.text, AnimatedErrorMessage.icon,
          AnimatedErrorMessage.iconColor - lib\shared\others.dart:72:7 - must_be_immutable
   info - The value of the field '_animationController' isn't used - lib\shared\others.dart:83:23 - unused_field
   info - The value of the local variable 'height' isn't used - lib\shared\others.dart:91:9 - unused_local_variable
   info - This class (or a class that this class inherits from) is marked as '@immutable', but one or more of its instance fields aren't final: LoadingAnimationName.text - lib\shared\others.dart:128:7 -
          must_be_immutable
   info - Unused import: 'package:zaa/pages/userMain.dart' - lib\shared\pageLogin.dart:4:8 - unused_import
   info - Unused import: 'package:zaa/shared/consts.dart' - lib\shared\pageLogin.dart:6:8 - unused_import
   info - The value of the field '_obsecure' isn't used - lib\shared\pageLogin.dart:54:8 - unused_field
   info - The value of the local variable 'height' isn't used - lib\shared\pageLogin.dart:72:5 - unused_local_variable
   info - The value of the local variable 'sS' isn't used - lib\shared\pageLogin.dart:74:5 - unused_local_variable
   info - Unused import: 'dart:convert' - lib\shared\private.dart:4:8 - unused_import
   info - Unused import: 'package:zaa/shared/globals.dart' - lib\shared\private.dart:6:8 - unused_import
   info - Unused import: 'package:flutter/foundation.dart' - lib\shared\private.dart:7:8 - unused_import
   info - Unused import: 'package:http/http.dart' - lib\shared\private.dart:8:8 - unused_import
   info - Unused import: 'package:shared_preferences/shared_preferences.dart' - lib\shared\private.dart:9:8 - unused_import
   info - Unused import: 'package:zaa/shared/classesHTTP.dart' - lib\shared\private.dart:11:8 - unused_import
   info - Unused import: 'package:http/http.dart' - lib\shared\private.dart:12:8 - unused_import
```

**Comment by 404King** [comment] 2020-07-21 06:09
同求这个问题，debug运行可以，打包就出问题。

**Comment by fabiocarneiro** [comment] 2020-10-08 01:37
make sure you have `<uses-permission android:name="android.permission.INTERNET" />` in `AndroidManifest.xml`

https://flutter.dev/docs/development/data-and-backend/networking

**Comment by jamesblasco** [comment] 2020-10-11 09:26
Please, could you provide some reproducible example? 

This looks more like the inner children are not being rendered due to a problem with that widget and not this package

**Comment by letsar** [comment] 2021-12-12 18:17
Closing since no answer

**Closed by letsar** 2021-12-12 18:17 UTC
Labels: waiting-response
