### ISSUE TITLE
StaggeredGridView.countBuilder doesn't  stretch to fit its content when scroll diraction is horizontal 

### ISSUE THREAD

**Issue by bero93** [letsar/flutter_staggered_grid_view#117] opened 2020-05-08 08:03 UTC
![Capture](https://user-images.githubusercontent.com/13046276/81384986-3fdfd680-911b-11ea-8d2d-685da22ea7fb.PNG)

this is the wanted result with an image inside each box that resize according to its width,

**Comment by jamesblasco** [comment] 2020-10-11 09:21
Duplicate of https://github.com/letsar/flutter_staggered_grid_view/issues/91

**Closed by jamesblasco** 2020-10-11 09:21 UTC
