### ISSUE TITLE
[Desktop] Auto adjust column/width on width change

### ISSUE THREAD

**Issue by bibijaan** [letsar/flutter_staggered_grid_view#138] opened 2020-10-17 06:52 UTC
When I expand width or reduce the width in desktop, it doesn't change it's column, unless a refresh.

![image](https://user-images.githubusercontent.com/72033357/96330490-682f1200-1077-11eb-8496-965d5a4a5463.png)

**Comment by rydmike** [comment] 2020-10-27 09:10
@letsar This is the bug I have been seeing since forever too and I might have mentioned in a Tweet. 

Thanks @bibijaan for reporting it, I have been too lazy to report it. The behavior I have seen is indeed that if you change only the width, it sometimes does not refresh, but by changing the height at the same time it will refresh.

I have also notice that when you resize just the width, it can also drop items!

I have really ancient live web demo if it running here: 

https://rydmike.com/gridtest/#/

If you select the Staggered Grid demo:
![image](https://user-images.githubusercontent.com/39990307/97278921-ff982000-1842-11eb-930d-400d87ff82ac.png)

You get something like this:
![image](https://user-images.githubusercontent.com/39990307/97279422-ad0b3380-1843-11eb-9102-1db62da83a7b.png)

and then do just a horizontal resize, it may sometimes drop items, like so:
![image](https://user-images.githubusercontent.com/39990307/97279532-c7dda800-1843-11eb-97b8-85ec5f9098b7.png)

And a height resize will bring them back:
![image](https://user-images.githubusercontent.com/39990307/97279613-de83ff00-1843-11eb-82fa-1a8d39ce8e6f.png)

And like you mentioned, sometimes it does not refresh at all:
![image](https://user-images.githubusercontent.com/39990307/97279666-f3f92900-1843-11eb-8f58-25bfd45e10b7.png)

----

**Disclaimer:** 

The build for the above linked Web example is from a really ancient Flutter version by now and probably an older StaggeredGridView version too, so the situation might have changed. I have however still observed the behavior in recent apps using the Staggered Grid View too, so I think the issue is still there.

I will update all to latest versions and make the example simpler and provide a link to the demo code in a Gist. Putting this on my TODOs for this issue report. I should have an updated demo of it later today or tomorrow.

**Comment by clragon** [comment] 2020-11-05 18:34
I'm having a similar issue that is probably linked to this one;

changing the cross axis count with setstate will not do anything until you literally scrap the route and get a new one.
changing the size of the tiles will lead to the same behaviour above: items completely disappear from the grid until the route is rebuilt from scratch.

very weird issue, very annoying too because I would like to be able to change the cross axis count on the fly.

**Comment by tomosullivan8** [comment] 2020-11-27 09:06
@rydmike did you manage to find anything further on this? I'm having the same issue where the `crossAxisCount` doesn't appear to be obeying the int given based on specific breakpoints.

I had been through my breakpoints and I couldn't seem to find an issue, so I started to use the [AdaptiveBreakpoints](https://pub.dev/packages/adaptive_breakpoints) package but I have the same issue still, and came across this when trying to see if anyone else had the same problem.

**Comment by tomosullivan8** [comment] 2020-12-24 14:59
I managed to get around the issue, changing the `SliverStraggeredGrid.countBuilder` to a `StaggeredGridView.countBuilder` and wrapping in a `SliverFillRemaining`.

Not ideal, but a fix for now.

**Comment by rydmike** [comment] 2021-01-07 12:51
@tomosullivan8  Sadly I have not had time to look into this issue either. Considering how popular this package is and that this is a really critical for Web usage (and desktop) of it, I'm a bit surprised @letsar has not looked into it himself. I don't think the issue shows up on tablets/phones since you can't resize just one dimension, on orientation change both dimensions change at the same time, and that kind of resize seems to work on desktop/web resize too.

I have it on my todo list to clone the repo and see I can find the issue. Then again I saw some mention of another package for similar layout that was reported to not have this issue, but I forgot what it was called, besides I like this one... 😄

**Comment by clragon** [comment] 2021-01-07 13:16
@rydmike I'm having an issue that might be related to this one, on phone and tablets, where updating the `crossAxisCount` on a `StaggeredGridView.countBuilder` with setState will result in emptiness instead of the tiles moving to fill the new columns. 
The only way to resolve this is by completely scrapping and rebuilding the widget.

**Comment by tomosullivan8** [comment] 2021-02-21 20:34
The issue I had was when changing the desktop window size the panels wouldn't correctly adjust unless it was resized to a specific size. I was using the Adaptive_Breakpoints package for screen sizes, so added the below `key` which makes the panels resize correctly.

`key: ValueKey<AdaptiveWindowType>(getWindowType(context))`

**Comment by clragon** [comment] 2021-06-15 15:48
@rydmike it seems like the issue doesnt happen on your grid demo anymore, did you find a workaround?

**Comment by rydmike** [comment] 2021-11-01 20:00
Thanks, I was just checking up on the status of issue. This does indeed work, not super smooth, but at least it works and for my use case right now that is good enough.

This is the same issue and workaround: https://github.com/letsar/flutter_staggered_grid_view/issues/167

cc @letsar

**Comment by rydmike** [comment] 2021-11-05 14:24
To readers of this issue, this comment in its same/related issue might be of interest too: https://github.com/letsar/flutter_staggered_grid_view/issues/167#issuecomment-961937316

**Comment by letsar** [comment] 2021-12-12 18:21
Can you test with the latest 0.5.0 preview? https://pub.dev/packages/flutter_staggered_grid_view/versions/0.5.0-dev.1

**Comment by rydmike** [comment] 2021-12-13 14:56
@letsar a test of the new version using the Masonry layout is shown and demonstrated as a web build here:
https://rydmike.com/gridtest-0-5-0-dev-1/#/

This [blog post](https://rydmike.com/gridview) describes the detection of the issue already in 2019. I used the same demo from 2019, but migrated to null-safety and built with latest Flutter 2.8.0. 

In StaggeredGridView 0.4.1 the same issue from 2019 is still present. I could however no longer repeat or see the issue in version 0.5.1-dev.1. The updated [blog post](https://rydmike.com/gridview) about it has more details for those interested and link to test repo.

Imo the issue can be closed.

**Comment by letsar** [comment] 2021-12-13 17:53
Thanks @rydmike this feedback and your blog post are very useful!
I'm closing this issue then 🙂

**Closed** 2021-12-13 17:54 UTC
Labels: waiting-response
