### ISSUE TITLE
Unable to scroll view when staggered grid is displayed

### ISSUE THREAD

**Issue by gastonche** [letsar/flutter_staggered_grid_view#11] opened 2018-06-20 14:09 UTC
I have this code 
```
_videosSection(){
    return new Column(
      children: <Widget>[
        new Padding(
          padding: const EdgeInsets.only(top: 8.0),
          child: Text(
            "Top Video Picks",
            style: Theme.of(context).textTheme.title,
          ),
        ),
        Container(
            child:  StaggeredGridView.countBuilder(
              crossAxisCount: 4,
              itemCount: videos == null ? 0: videos.length,
              shrinkWrap: true,
              itemBuilder: (BuildContext context, int index) => GraphicPreview(videos.elementAt(index)),
              staggeredTileBuilder: (int index) => new StaggeredTile.count(2, index.isEven ? 2 : 1),
              mainAxisSpacing: 0.0,
              crossAxisSpacing: 0.0,
            )
        ),
      ],
    );
  }
```

but once the view is rendered, the page is no scrollable anymore. When i try to scroll, it shows an accent showing as if it's trying to scroll inside the staggered grid. Any idea what's wrong with my code?

**Comment by letsar** [comment] 2018-06-20 15:38
Hi @gastonche, I think you should use a `CustomScrollView` with two slivers here:
A `SliverPadding` (to replace the `Padding` widget)
A `SliverStaggeredGrid`(to replace the `StaggeredGridView`).
The issue here is because the `Column`does not let you to scroll.

**Comment by FatihAydin52** [comment] 2019-05-27 18:38
i have same issue.
```

StaggeredGridView.countBuilder(
      crossAxisCount: 2,
      staggeredTileBuilder: (index) => new StaggeredTile.fit(2),
      itemCount: data.results.length,
      itemBuilder: (context, index) {
        return Card(
          color: Colors.transparent,
          clipBehavior: Clip.antiAlias,
          elevation: 0,
          child: ClipRRect(
            borderRadius: BorderRadius.all(Radius.circular(10)),
            child: Column(
              children: <Widget>[
                CachedNetworkImage(
                  imageUrl: data.results[index].image,
                ),
                Container(
                  color: Colors.white,
                  padding: EdgeInsets.all(10),
                  child: Column(
                    children: <Widget>[
                      Row(
                        mainAxisAlignment: MainAxisAlignment.spaceBetween,
                        children: <Widget>[
                          Text(
                            data.results[index].channel.name,
                            style: TextStyle(
                              fontSize: 14,
                              color: Colors.black54,
                            ),
                          ),
                          Text(
                            data.results[index].publishDate.toIso8601String(),
                            style: TextStyle(
                              fontSize: 14,
                              color: Colors.black54,
                            ),
                          )
                        ],
                      ),
                      Padding(
                        padding: EdgeInsets.symmetric(vertical: 10),
                        child: Text(
                          data.results[index].title,
                          style: TextStyle(
                              fontWeight: FontWeight.bold,
                              fontSize: 18,
                              color: Colors.black87),
                        ),
                      ),
                      Text(
                        data.results[index].description,
                        style: TextStyle(
                          color: Colors.black54,
                          fontSize: 14,
                        ),
                      )
                    ],
                  ),
                )
              ],
            ),
          ),
        );
      },
    );
```

**Comment by arutkayb** [comment] 2019-08-18 20:51
I'm having the same problem but SliverStaggeredGrid.count inside CustomScrollView is not solving my problem. Can you have a look? Reproduce: https://github.com/arutkayb/FlutterMovies/tree/f17c2fb3c85275ccf87f25d89b834dedc5ce13fe

**Comment by khalidsaleh** [comment] 2019-10-14 16:14
StaggeredGridView and SliverStaggeredGrid not scrolling !!!!!!!!

**Comment by letsar** [comment] 2021-12-06 20:40
Closing as it resolved or will not be fixed in the current version (a new version, completely refactored is on its way).
Let me know If you can test under the feature/renaissance branch, and it's not resolved.

**Closed by letsar** 2021-12-06 20:40 UTC

**Comment by lucasjinreal** [comment] 2024-06-23 14:57
Still can not scrolling....

I am not sure why a popular gridView can not be scrolled default....
