### ISSUE TITLE
I am getting this, do you know how I am wrong ? @@

### ISSUE THREAD

**Issue by dinhan1192** [letsar/flutter_staggered_grid_view#131] opened 2020-08-06 09:36 UTC
![image](https://user-images.githubusercontent.com/42635147/89516661-efa00f80-d802-11ea-8e55-b1fe37af5576.png)
![image](https://user-images.githubusercontent.com/42635147/89516724-ff1f5880-d802-11ea-8c03-aaf8d14a0ab7.png)

**Comment by agnamc9** [comment] 2020-08-29 11:36
Can you share the code of your ```listInside(...)``` ?

**Comment by jamesblasco** [comment] 2020-10-10 12:11
Please add some reproducible code of this issue so we can help you

**Comment by letsar** [comment] 2021-12-12 18:18
Closing since no answer

**Closed by letsar** 2021-12-12 18:18 UTC
Labels: waiting-response
