### ISSUE TITLE
Failed assertion: line 2653 pos 12: '!_needsLayout'

### ISSUE THREAD

**Issue by gabrielamota29** [letsar/flutter_staggered_grid_view#189] opened 2021-07-06 09:50 UTC
I will investigate how I got the error since It happened and I was not paying attention to the part of the code that I was executing.

Here are the logs:

════════ Exception caught by scheduler library ═════════════════════════════════
The following assertion was thrown during a scheduler callback:
Updated layout information required for RenderIndexedSemantics#31dd4 NEEDS-LAYOUT NEEDS-PAINT to calculate semantics.
'package:flutter/src/rendering/object.dart':
Failed assertion: line 2653 pos 12: '!_needsLayout'

2

Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
https://github.com/flutter/flutter/issues/new?template=2_bug.md

When the exception was thrown, this was the stack
#2 RenderObject._getSemanticsForParent
package:flutter/…/rendering/object.dart:2653
#3 RenderObject._getSemanticsForParent.
package:flutter/…/rendering/object.dart:2675
#4 Iterable.forEach (dart:core/iterable.dart:257:30)
#5 RenderSliverVariableSizeBoxAdaptor.visitChildren
package:flutter_staggered_grid_view/…/rendering/sliver_variable_size_box_adaptor.dart:296
#6 RenderObject.visitChildrenForSemantics
package:flutter/…/rendering/object.dart:2760
...
════════════════════════════════════════════════════════════════════════════════
Also mentioned here https://github.com/flutter/flutter/issues/84173.

**Comment by EdsonBueno** [comment] 2021-07-10 19:19
Same here.

**Comment by alvinchan88** [comment] 2021-07-11 02:03
Confirmed.  Getting the same issue on iOS

**Comment by teoprayoga** [comment] 2021-07-11 08:05
same issue on IOS device

**Comment by nivla360** [comment] 2021-07-17 15:02
same issue here...

**Comment by Klabauterman** [comment] 2021-07-19 07:49
It looks like it is related to overscrolling. It happens the first time you overscroll.

**Comment by nhathuynh77** [comment] 2021-07-30 07:02
Same issue here...   => crash app when releasing mode.

**Comment by karunstha** [comment] 2021-08-02 07:35
The same issue with the ios simulator when over scrolling for the first time.

**Comment by vHanda** [comment] 2021-08-13 07:58
I get the same issue, with android as well. Here is the smallest example that can reproduce it -

```dart
import 'package:flutter/material.dart';
import 'package:flutter/widgets.dart';
import 'package:flutter_staggered_grid_view/flutter_staggered_grid_view.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(context) {
    var gridView = StaggeredGridView.extentBuilder(
      itemCount: 100,
      itemBuilder: (BuildContext _, int __) => Container(
        width: 200,
        height: 200,
        color: Colors.amber,
      ),
      maxCrossAxisExtent: 200.0,
      staggeredTileBuilder: (int i) => const StaggeredTile.fit(1),
      mainAxisSpacing: 8.0,
      crossAxisSpacing: 8.0,
    );

    return MaterialApp(home: Scaffold(body: gridView));
  }
}

```

**Comment by teoprayoga** [comment] 2021-08-23 03:27
`
CustomScrollView(
   slivers: [
             BlocBuilder<FaskesCubit, FaskesState>(
             if (faskeses.length.isEmpty) {
                 return SliverBoxAdapter(child: ...);
             }
        return SliverStaggeredGrid.countBuilder(
                  crossAxisCount: 2,
                  itemCount: faskeses.length,
                  staggeredTileBuilder: (int index) => StaggeredTile.fit(
                    1,
                  ),
                  itemBuilder: (context, int) => Container(child: ...);
     )
   ]
),
`

**Comment by JDongKhan** [comment] 2021-09-07 02:47
Is anyone watching?

**Comment by kristoffer-zliide** [comment] 2021-09-08 09:29
Removing this change, the error seems to go away: https://github.com/zliide/flutter_staggered_grid_view/commit/eee016faa2d2b82b8021cb374e6dfdba0f63db6d#diff-a6463fff503aa4550bba44e92347adc59125a1de07cff0211b732f8475f9b3e7

**Comment by bookyo** [comment] 2021-09-09 03:42
same issue in NestedScrollView and in CustomScrollView. how to sovle it?

**Comment by vHanda** [comment] 2021-09-29 14:25
> Removing this change, the error seems to go away: [eee016f#diff-a6463fff503aa4550bba44e92347adc59125a1de07cff0211b732f8475f9b3e7](https://github.com/letsar/flutter_staggered_grid_view/commit/eee016faa2d2b82b8021cb374e6dfdba0f63db6d#diff-a6463fff503aa4550bba44e92347adc59125a1de07cff0211b732f8475f9b3e7)

@kristoffer-zliide : How did you figure this out? Did you just do a git bisect and/or revert commits?

I ask as this widget is very important for my app, and I barely understand its implementation. If you could point me to anything that helped you understand it, I would appreciate it.

**Comment by kristoffer-zliide** [comment] 2021-09-29 15:47
@vHanda: sorry, I have no clue how it works either, but due to [this issue](https://github.com/letsar/flutter_staggered_grid_view/issues/91), we maintain [a fork](https://github.com/zliide/flutter_staggered_grid_view) that just happened to be created just before the mentioned commit and when we recently rebased the fork, we immediately hit this issue.

**Comment by kristoffer-zliide** [comment] 2021-09-29 15:49
@BertrandBev: do you know what's going on here?

**Comment by alvinchan88** [comment] 2021-11-17 17:35
Setting shrinkWrap to true fixed it for me.

**Comment by InAnadea** [comment] 2021-12-07 09:56
Same for me!

**Comment by JDongKhan** [comment] 2021-12-07 09:56
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by InAnadea** [comment] 2021-12-07 11:18
> @vHanda: sorry, I have no clue how it works either, but due to [this issue](https://github.com/letsar/flutter_staggered_grid_view/issues/91), we maintain [a fork](https://github.com/zliide/flutter_staggered_grid_view) that just happened to be created just before the mentioned commit and when we recently rebased the fork, we immediately hit this issue.

Create pull request on this repo

**Comment by letsar** [comment] 2021-12-12 18:37
Can you test with the latest 0.5.0 preview? https://pub.dev/packages/flutter_staggered_grid_view/versions/0.5.0-dev.1

**Comment by XOneto9** [comment] 2022-02-28 17:56
In my case, I changed code from StaggeredTile.fit to StaggeredTile.count
it is solved.


instead of 
```
      staggeredTileBuilder: (int i) => const StaggeredTile.fit(1),

```

apply to,

```
      staggeredTileBuilder: (int i) => const StaggeredTile.count(1, 1.2),

```

* but, I'm using 0.4.1 version

However,  The changed StaggeredTile with count is not make error any more.

**Comment by JDongKhan** [comment] 2022-02-28 17:57
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by letsar** [comment] 2022-07-10 08:56
Seems to be solved. Closing this.

**Closed by letsar** 2022-07-10 08:56 UTC
Labels: waiting-response
